### ISSUE TITLE
Other backbone implements and related pre-trained model

### ISSUE THREAD

**Issue by seabearlmx** [suhyeonlee/WildNet#4]
Hi, thanks for your insight work!

Could you provide the implementation of your proposed approach based on the VGG-16 backbone?

and provide the initial pre-trained model of the ResNet-50 and VGG-16 backbone or their download links?

**Comment by suhyeonlee** [comment]
Hi,

Thanks for your interest.

Our ResNet-50 model has been provided on [Google Drive](https://drive.google.com/file/d/1O4QXQqYq-vuukQc5HGZlun914FuFf13a/view) and there are no plans to release other backbone implementations and pre-trained models.
