### ISSUE TITLE
Link to pretrained model is not working 

### ISSUE THREAD

**Issue by waychin-weiqin** [suhyeonlee/WildNet#5]
Hi, 

First of all, thank you for the great work and also for publishing your code. 

I am trying to replicate the results you have included in the paper, using the pretrained model. However, it seems like the link to the google drive you have attached is not working. Could you have a look into that please? 

Thank you.

**Comment by suhyeonlee** [comment]
Hi,

Thanks for your interest.

The google drive link is now fixed.
